/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSpout */

#ifndef _Included_JSpout
#define _Included_JSpout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSpout
 * Method:    InitSender
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_JSpout_InitSender
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     JSpout
 * Method:    InitReceiver
 * Signature: (Ljava/lang/String;[II)I
 */
JNIEXPORT jint JNICALL Java_JSpout_InitReceiver
  (JNIEnv *, jclass, jstring, jintArray, jint);

/*
 * Class:     JSpout
 * Method:    ReleaseSender
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_ReleaseSender
  (JNIEnv *, jclass);

/*
 * Class:     JSpout
 * Method:    ReleaseReceiver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_ReleaseReceiver
  (JNIEnv *, jclass);

/*
 * Class:     JSpout
 * Method:    WriteToSharedMemory
 * Signature: (II[I)Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_WriteToSharedMemory
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     JSpout
 * Method:    ReadFromSharedMemory
 * Signature: ([I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_ReadFromSharedMemory
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     JSpout
 * Method:    ReadTexture
 * Signature: ([I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_ReadTexture
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     JSpout
 * Method:    WriteTexture
 * Signature: (IIIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_WriteTexture
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean);

/*
 * Class:     JSpout
 * Method:    GetSenderName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JSpout_GetSenderName
  (JNIEnv *, jclass);

/*
 * Class:     JSpout
 * Method:    SenderDialog
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_SenderDialog
  (JNIEnv *, jclass);

/*
 * Class:     JSpout
 * Method:    CreateControl
 * Signature: (Ljava/lang/String;Ljava/lang/String;FFFLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_CreateControl
  (JNIEnv *, jclass, jstring, jstring, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     JSpout
 * Method:    OpenControls
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_OpenControls
  (JNIEnv *, jclass, jstring);

/*
 * Class:     JSpout
 * Method:    CheckControls
 * Signature: ([Ljava/lang/String;[I[F[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JSpout_CheckControls
  (JNIEnv *, jclass, jobjectArray, jintArray, jfloatArray, jobjectArray);

/*
 * Class:     JSpout
 * Method:    CloseControls
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JSpout_CloseControls
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
