//
// Header: SpoutCommon.h
//
// Enables build of the SDK as a DLL.
//
// Includes header for common utilities namespace "SpoutUtils".
//
// Optional _#define legacyOpenGL_ to enable legacy draw functions
//

/*
		Thanks and credit to Malcolm Bechard, the author of this file
		https://github.com/mbechard

		Copyright (c) 2014-2023, Lynn Jarvis. All rights reserved.

		Redistribution and use in source and binary forms, with or without modification, 
		are permitted provided that the following conditions are met:

		1. Redistributions of source code must retain the above copyright notice, 
		   this list of conditions and the following disclaimer.

		2. Redistributions in binary form must reproduce the above copyright notice, 
		   this list of conditions and the following disclaimer in the documentation 
		   and/or other materials provided with the distribution.

		THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"	AND ANY 
		EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
		OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE	ARE DISCLAIMED. 
		IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
		INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
		PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
		INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
		LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
		OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


*/
#pragma once

#ifndef __SpoutCommon__
#define __SpoutCommon__
//
// For build of the Spout library as a dll
//
#if defined(_MSC_VER)
	#if defined(SPOUT_BUILD_DLL)
		#define SPOUT_DLLEXP	__declspec(dllexport)
	#elif defined(SPOUT_IMPORT_DLL)
		#define SPOUT_DLLEXP	__declspec(dllimport)
	#else
		#define SPOUT_DLLEXP
	#endif
#else // _MSC_VER
	#define SPOUT_DLLEXP
#endif // _MSC_VERR

// Common utility functions namespace
#include "SpoutUtils.h"

//
// This definition enables legacy OpenGL rendering code
// used for shared texture Draw functions in SpoutGLDXinterop.cpp
// Not required unless compatibility with OpenGL < 3 is necessary
// Disabled by default for OpenGL 4 compliance
// * Note that the same definition is necessary in SpoutGLextensions.h
//   so that SpoutGLextensions can be used independently of the Spout library.
//
// #define legacyOpenGL
//

//
// Visual Studio code analysis warnings
//

// C++11 scoped (class) enums are not compatible with early compilers (< VS2012 and others).
// The warning is designated "Prefer" and "C" standard unscoped enums are retained for compatibility.
#pragma warning(disable:26812) // unscoped enums

//
// The following warnings were generated by Visual Studio code analysis
// using the "Microsoft all rules" rule set and can be disabled pending re-write.
// All functions checked and changed where possible.
// "Microsoft Native Recommended rules" produce no warnings.
/*
#pragma warning(disable : 26440) // Function can can be declared 'noexcept' (not desirable)
#pragma warning(disable : 26455) // Declare default constructor 'noexcept' (not desirable)
#pragma warning(disable : 26432) // Define or delete them all  (not desirable)
#pragma warning(disable : 26481) // Don't use pointer arithmetic (unavoidable with present methods)
#pragma warning(disable : 26490) // Don't use reinterpret_cast (removing results in further warnings)
#pragma warning(disable : 26493) // C-style casts (removing results in further warnings)
#pragma warning(disable : 26408) // avoid malloc and free (preference only)
#pragma warning(disable : 26826) // va_list etc. (unavoidable with logging methods)
#pragma warning(disable : 26485) // Array as a single pointer (standard library functions can't be changed)
#pragma warning(disable : 26135) // Missing annotation _Acquires_lock/_Releases_lock_ (cannot implement)
#pragma warning(disable : 26482) // Only index into arrays using constant expressions (indices are always in range)
#pragma warning(disable : 26446) // Prefer to use gsl::at() (dependence on gls library undesirable)
#pragma warning(disable : 26409) // Avoid calling new and delete explicitly (std::make_unique is used where possible)
#pragma warning(disable : 26400) // Do not return value to a raw pointer (original author of the file should be consulted)
*/


#endif
