/*
=========================================================================

                       ReceiverWindows.cpp

					Basic OpenGL Spout receiver

   A Windows Desktop Application project generated by Visual Studio
   and adapted for Spout input (http://spout.zeal.co/).

   This is an example using ReceiveTexture and ReceiveImage

   bool ReceiveTexture(GLuint TextureID = 0, GLuint TextureTarget = 0, bool bInvert = false, GLuint HostFbo = 0)
   bool ReceiveImage(unsigned char* pixels, GLenum glFormat, bool bInvert, GLuint HostFbo)

   Receives to a pixel buffer or to a texture texture and reads to a pixel buffer
   Displays the  pixel buffer using Windows bitmap functions.

   Search on "SPOUT" for additions.

   Compare with the Openframeworks "Receiver > Graphics" example
   Compare also with the basic Windows OpenGL sender example.

	---------------------------------------------------------------------------

                 Copyright(C) 2024-2025 Lynn Jarvis.

This program is free software : you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.If not, see < http://www.gnu.org/licenses/>.
========================================================================

*/
#include "framework.h"
#include "ReceiverWindows.h"

#define MAX_LOADSTRING 100

// Global Variables:
HINSTANCE hInst;                       // current instance
WCHAR szTitle[MAX_LOADSTRING]{};       // The title bar text
WCHAR szWindowClass[MAX_LOADSTRING]{}; // the main window class name

// SPOUT
Spout receiver;                         // Receiver object
HWND g_hWnd = NULL;                     // Window handle
unsigned char *g_pixelBuffer = nullptr; // Receiving pixel buffer
GLuint g_TextureGL = 0;                 // ReceiveTexture example
unsigned char g_SenderName[256]{};      // Received sender name
unsigned int g_SenderWidth = 0;         // Received sender width
unsigned int g_SenderHeight = 0;        // Received sender height
DWORD g_SenderFormat = 0;               // Received sender format
bool bShowInfo = true;                  // Show onscreen details
double g_SenderFps = 0.0;               // Sender framerate

// Forward declarations of functions included in this code module:
ATOM                MyRegisterClass(HINSTANCE hInstance);
BOOL                InitInstance(HINSTANCE, int);
LRESULT CALLBACK    WndProc(HWND, UINT, WPARAM, LPARAM);

// SPOUT
void Render();
void ShowSenderInfo(HDC hdc); // Show sender information on screen
void DrawString(std::string str, HDC hdc, COLORREF col, int xpos, int ypos); // Draw text


int APIENTRY wWinMain(_In_ HINSTANCE hInstance,
                     _In_opt_ HINSTANCE hPrevInstance,
                     _In_ LPWSTR    lpCmdLine,
                     _In_ int       nCmdShow)
{
    UNREFERENCED_PARAMETER(hPrevInstance);
    UNREFERENCED_PARAMETER(lpCmdLine);

    // Initialize global strings
    LoadStringW(hInstance, IDS_APP_TITLE, szTitle, MAX_LOADSTRING);
    LoadStringW(hInstance, IDC_WINSPOUTGL, szWindowClass, MAX_LOADSTRING);
    MyRegisterClass(hInstance);

    // Perform application initialization:
    if (!InitInstance (hInstance, nCmdShow))
    {
        return FALSE;
    }

	// SPOUT
	// Initialize OpenGL
	if (!receiver.CreateOpenGL())
		return FALSE;

	// Option - enable Spout logging
	// EnableSpoutLog(); // Log to console
	// Or open an empty console for debugging
	// OpenSpoutConsole();

	// Option - set the name of the sender to receive from
	// The receiver will only connect to that sender.
	// The user can over-ride this by selecting another.
	// receiver.SetReceiverName("Spout DX11 Sender");

	// Pre-allocate a receiving texture for "Option 3"
	// This can be any size or format
	g_SenderWidth  = 1920;
	g_SenderHeight = 1080;
	receiver.InitTexture(g_TextureGL, GL_RGBA, g_SenderWidth, g_SenderHeight);
	// And the pixel buffer for WM_PAINT
	g_pixelBuffer = new unsigned char[g_SenderWidth*g_SenderHeight*4];

		
	// Main message loop:
	MSG msg = { 0 };
	while (WM_QUIT != msg.message)
	{
		if (PeekMessage(&msg, nullptr, 0, 0, PM_REMOVE))
		{
			TranslateMessage(&msg);
			DispatchMessage(&msg);
		}
		Render();
	}

	// SPOUT

	// Release resources
	if (g_pixelBuffer)
		delete[] g_pixelBuffer;

	if(g_TextureGL > 0)
		glDeleteTextures(1, &g_TextureGL);

	// Release the receiver
	receiver.ReleaseReceiver();

	// Release OpenGL
	receiver.CloseOpenGL();

    return (int) msg.wParam;
}

// SPOUT
void Render()
{
	//
	// ReceiveImage and ReceiveTexture connect to and receive from a sender
	// and handle sender detection, receiver creation and update.
	//
	// For successful receive, sender details can be retrieved with
	//		const char* GetSenderName();
	//		unsigned int GetSenderWidth();
	//		unsigned int GetSenderHeight();
	//		DWORD GetSenderFormat();
	//		double GetSenderFps();
	//		long GetSenderFrame();
	//
	// If receive fails, the sender has closed
	// Connection can be tested at any time with 
	//		bool IsConnected();
	//
	// Compare with the Openframeworks ofSpoutExample "Receiver > Graphics" example
	// for additional options :
	//

	//
	// OPTION 1) - Receive image pixels
	//

	/*
	//
	// Get pixels from the sender shared texture
	//
	// Format can be GL_RGBA, GL_BGRA, GL_RGB or GL_BGR for the receving buffer.
	// Specify GL_BGRA for this example to match with Windows bitmap draw in WM_PAINT.
	// Data received from a sender is then converted to BGRA for return.
	//
	// Because Windows bitmaps are bottom-up, the pixel buffer is flipped
	// here ready for WM_PAINT but it could also be drawn upside down.
	if (receiver.ReceiveImage(g_pixelBuffer, GL_BGRA, true)) {
		// IsUpdated() returns true if the sender has changed
		if (receiver.IsUpdated()) {
			// Update the sender name - it could be different
			strcpy_s((char *)g_SenderName, 256, receiver.GetSenderName());
			// Update globals
			g_SenderWidth = receiver.GetSenderWidth();
			g_SenderHeight = receiver.GetSenderHeight();
			g_SenderFormat = receiver.GetSenderFormat();
			// Update the receiving buffer
			if (g_pixelBuffer) delete[] g_pixelBuffer;
			g_pixelBuffer = new unsigned char[g_SenderWidth*g_SenderHeight*4];
		}
	}
	*/

	/*
	//
	// OPTION 2) - Receive texture
	//
	if (receiver.ReceiveTexture(g_TextureGL, GL_TEXTURE_2D)) {

		// IsUpdated() returns true if the sender has changed
		if (receiver.IsUpdated()) {

			// Update the sender name - it could be different
			strcpy_s((char *)g_SenderName, 256, receiver.GetSenderName());

			//
			// Allocate or re-allocate the receiving texture
			//
			// o The width and height can be any value
			//   and the texture can be pre-allocated.
			//   Typically the sender dimensions are used
			//   and the texture is allocated here.
			// o The format must be GL_RGBA GL_RGBA8 or GL_BGRA
			//   (8 bit pixel data type) in this example to match
			//   with the Windows bitmap in WM_PAINT.
			//

			// Update the receiving texture
			if(g_TextureGL)	glDeleteTextures(1, &g_TextureGL);
			g_SenderWidth  = receiver.GetSenderWidth();
			g_SenderHeight = receiver.GetSenderHeight();
			receiver.InitTexture(g_TextureGL, GL_RGBA, g_SenderWidth, g_SenderHeight);

			// And the pixel buffer for WM_PAINT
			if (g_pixelBuffer) delete[] g_pixelBuffer;
			g_pixelBuffer = new unsigned char[g_SenderWidth*g_SenderHeight*4];

			// Return here because the texture will be empty
			// The sender texture is received on the next frame
			return;
		}

		// Read pixels from the texture
		// Copy is optimised using OpenGL pixel buffers if available.
		// For this example, specify GL_BGRA pixel data format and
		// unsigned byte type to match with the Windows bitmap in WM_PAINT.
		// Invert true for bottom-up Windows bitmap.
		receiver.ReadTextureData(g_TextureGL, GL_TEXTURE_2D, g_pixelBuffer,
			g_SenderWidth, g_SenderHeight, g_SenderWidth*4,
			GL_BGRA, GL_UNSIGNED_BYTE, true);
	}
	*/

	//
	// Option 3 : Receive to a pre-allocated OpenGL texture
	//
	// The sender texture is fitted to the receiving texture size
	//
	if (receiver.ReceiveTexture(g_TextureGL, GL_TEXTURE_2D)) {
		//
		// IsUpdated() returns true if the sender has changed
		// It is optional for a pre-allocated texture.
		//
		// Read pixels from the texture
		receiver.ReadTextureData(g_TextureGL, GL_TEXTURE_2D, g_pixelBuffer,
			g_SenderWidth, g_SenderHeight, g_SenderWidth*4,
			GL_BGRA, GL_UNSIGNED_BYTE, true);
	}

	/*
	//
	// Option 4 : Receive an OpenGL shared texture to access directly.
	//
	// Only if compatible for GL/DX interop or else BindSharedTexture fails.
	// For this example, read pixels from the shared texture. 
	// The texture binding can be be used directly for other functions.
	//
	if (receiver.ReceiveTexture()) {

		// IsUpdated() returns true if the sender has changed
		// It is optional if accessing the sender texture directly
		// but here the receiving pixel buffer has to be re-allocated
		if (receiver.IsUpdated()) {
			g_SenderWidth  = receiver.GetSenderWidth();
			g_SenderHeight = receiver.GetSenderHeight();
			if (g_pixelBuffer) delete[] g_pixelBuffer;
			g_pixelBuffer = new unsigned char[g_SenderWidth*g_SenderHeight*4];
		}

		// 1. Get access to the sender DirectX shared texture
		// 2. Lock the interop to get access to the linked OpenGL texture
		// 3. Bind the OpenGL texture
		if (receiver.BindSharedTexture()) {

			// ------------------------------------------------
			// With the sender OpenGL texture bound,
			// read the texture to pixels using glGetTexImage
			// as an example of using low level OpenGL functions.
			// Specify GL_BGRA for the returned data for WM_PAINT.
			// In this example only 4 component unsigned byte
			// data is suitable, Other sender formats will fail.
			glGetTexImage(GL_TEXTURE_2D, 0, GL_BGRA,
				GL_UNSIGNED_BYTE, (void*)g_pixelBuffer);
			// Flip the pixel buffer in place because
			// DirectX and OpenGL texture origins are inverted
			receiver.spoutcopy.FlipBuffer(g_pixelBuffer,
				g_SenderWidth, g_SenderHeight, GL_BGRA);
			// ------------------------------------------------

			// For other formats, ReadTextureData can be used
			// receiver.ReadTextureData(receiver.GetSharedTextureID(),
				// GL_TEXTURE_2D, g_pixelBuffer,
				// g_SenderWidth, g_SenderHeight, g_SenderWidth*4,
				// GL_BGRA, GL_UNSIGNED_BYTE, true);

			// 1. Un-bind the OpenGL texture
			// 2. Unlock the interop
			// 3. Release access to texture
			receiver.UnBindSharedTexture();
		}
	}
	*/

	// Trigger a re-paint to draw the pixel buffer - see WM_PAINT
	InvalidateRect(g_hWnd, NULL, FALSE);
	UpdateWindow(g_hWnd); // Update immediately

	// Hold a target frame rate - e.g. 60 or 30fps.
	// Not necessary if the application already has fps control
	// but in this example, render rate can be extremely high if 
	// graphics driver "wait for vertical refresh" is disabled.
	receiver.HoldFps(60);

}


//
//  FUNCTION: MyRegisterClass()
//
//  PURPOSE: Registers the window class.
//
ATOM MyRegisterClass(HINSTANCE hInstance)
{
    WNDCLASSEXW wcex;

    wcex.cbSize = sizeof(WNDCLASSEX);

    wcex.style          = CS_HREDRAW | CS_VREDRAW;
    wcex.lpfnWndProc    = WndProc;
    wcex.cbClsExtra     = 0;
    wcex.cbWndExtra     = 0;
    wcex.hInstance      = hInstance;
    wcex.hIcon          = LoadIcon(hInstance, MAKEINTRESOURCE(IDI_WINSPOUTGL));
    wcex.hCursor        = LoadCursor(nullptr, IDC_ARROW);
	wcex.hbrBackground  = CreateHatchBrush(HS_DIAGCROSS, RGB(192, 192, 192));
    wcex.lpszMenuName   = MAKEINTRESOURCEW(IDC_WINSPOUTGL);
    wcex.lpszClassName  = szWindowClass;
	wcex.hIconSm = LoadIcon(wcex.hInstance, MAKEINTRESOURCE(IDI_WINSPOUTGL));

    return RegisterClassExW(&wcex);
}

//
//   FUNCTION: InitInstance(HINSTANCE, int)
//
//   PURPOSE: Saves instance handle and creates main window
//
//   COMMENTS:
//
//        In this function, we save the instance handle in a global variable and
//        create and display the main program window.
//
BOOL InitInstance(HINSTANCE hInstance, int nCmdShow)
{
   hInst = hInstance; // Store instance handle in our global variable

   // Create window
   RECT rc = { 0, 0, 640, 360 }; // Desired client size
   AdjustWindowRect(&rc, WS_OVERLAPPEDWINDOW, TRUE); // Allow for menu
   HWND hWnd = CreateWindowW(szWindowClass,
	   szTitle,
	   WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_MAXIMIZEBOX | WS_THICKFRAME,
	   CW_USEDEFAULT, CW_USEDEFAULT, rc.right - rc.left, rc.bottom - rc.top, nullptr, nullptr, hInstance,
	   nullptr);

   if (!hWnd)
   {
      return FALSE;
   }

   // SPOUT
   // Centre the window on the desktop work area
   GetWindowRect(hWnd, &rc);
   RECT WorkArea;
   int WindowPosLeft = 0;
   int WindowPosTop = 0;
   SystemParametersInfo(SPI_GETWORKAREA, 0, (LPVOID)&WorkArea, 0);
   WindowPosLeft += ((WorkArea.right  - WorkArea.left) - (rc.right - rc.left)) / 2;
   WindowPosTop  += ((WorkArea.bottom - WorkArea.top)  - (rc.bottom - rc.top)) / 2;
   MoveWindow(hWnd, WindowPosLeft, WindowPosTop, (rc.right - rc.left), (rc.bottom - rc.top), false);

   ShowWindow(hWnd, nCmdShow);
   UpdateWindow(hWnd);

   g_hWnd = hWnd;
   
   return TRUE;
}

//
//  FUNCTION: WndProc(HWND, UINT, WPARAM, LPARAM)
//
//  PURPOSE: Processes messages for the main window.
//
//  WM_COMMAND  - process the application menu
//  WM_PAINT    - Paint the main window
//  WM_DESTROY  - post a quit message and return
//
//
LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
{
    switch (message)
    {
		case WM_COMMAND:
        {
            int wmId = LOWORD(wParam);
            // Parse the menu selections:
            switch (wmId)
            {

			case IDM_ABOUT:
				{
					std::string about = "                  Windows OpenGL\n";
					about += "             Spout receiver example\n\n";
					about += " 'File > Select sender' or mouse right click\n";
					about += "    to choose the sender to receive from.\n\n";
					about += "               <a href=\"http://spout.zeal.co/\">http://spout.zeal.co</a>\n"; 
					// Custom icon for the SpoutMessagBox, activated by MB_USERICON
					SpoutMessageBoxIcon(LoadIconA(GetModuleHandle(NULL), MAKEINTRESOURCEA(IDI_WINSPOUTGL)));
					// Centre on the application window
					SpoutMessageBoxWindow(hWnd);
					SpoutMessageBox(NULL, (LPSTR)about.c_str(), "ReceiverWindows", MB_USERICON | MB_OK);
				}
				break;

			case IDM_SELECT:
				//
				// Select a sender
				//
				// The change is detected withion the Spout class
				// and the receiver switches to that sender.
				// IsUpdated() returns true so that resources can be updated
				// See details in Render()
				//
				receiver.SelectSender();
				break;

			case IDM_EXIT:
                DestroyWindow(hWnd);
                break;
            default:
                return DefWindowProc(hWnd, message, wParam, lParam);
            }
        }
        break;

	case WM_PAINT:
        {
			if (IsIconic(hWnd))
				break;

			PAINTSTRUCT ps{};
			HDC hdc = BeginPaint(hWnd, &ps);

			RECT dr{};
			GetClientRect(hWnd, &dr);
				
			// Create a double buffer so that both image and text
			// can be drawn o a memory DC to avoid flicker.
			HDC hdcMem = CreateCompatibleDC(hdc);
			int ndcmem = SaveDC(hdcMem);
			HBITMAP hbmMem = CreateCompatibleBitmap(hdc, (dr.right-dr.left), (dr.bottom-dr.top));
			SelectObject(hdcMem, hbmMem);

			//
			// Draw the received image
			//
			if (g_pixelBuffer) {

				// No sender - draw default background
				if (!receiver.IsConnected()) {
					HBRUSH backbrush = CreateHatchBrush(HS_DIAGCROSS, RGB(192, 192, 192));
					FillRect(hdc, &dr, backbrush);
					DeleteObject(backbrush);
				}
				else {
					BITMAPINFO bmi{};
					bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
					bmi.bmiHeader.biSizeImage = (LONG)(g_SenderWidth*g_SenderHeight*4); // Pixel buffer size
					bmi.bmiHeader.biWidth  = (LONG)g_SenderWidth;  // Width of buffer
					bmi.bmiHeader.biHeight = (LONG)g_SenderHeight; // Height of buffer (bottom up)
					bmi.bmiHeader.biPlanes = 1;
					bmi.bmiHeader.biBitCount = 32;
					bmi.bmiHeader.biCompression = BI_RGB;

					// Draw into the memory DC
					// The received texture format is BGRA, compatible with StretchDIBits
					// StretchDIBits adapts the pixel buffer to the window size.
					// Setting the blit mode is necessary here
					SetStretchBltMode(hdcMem, STRETCH_DELETESCANS);
					StretchDIBits(hdcMem,
						0, 0, (dr.right - dr.left), (dr.bottom - dr.top),
						0, 0, g_SenderWidth, g_SenderHeight, g_pixelBuffer,
						&bmi, DIB_RGB_COLORS, SRCCOPY);

					// Draw information text
					if (bShowInfo) ShowSenderInfo(hdcMem);

					// Copy the double buffer to screen
					BitBlt(hdc, 0, 0, (dr.right-dr.left), (dr.bottom-dr.top), hdcMem, 0, 0, SRCCOPY);
					
					// Clean up
					RestoreDC(hdcMem, ndcmem);
					DeleteObject(hbmMem);
					DeleteDC(hdcMem);

				}
			}
			EndPaint(hWnd, &ps);
        }
        break;

	// SPOUT
	case WM_RBUTTONDOWN:
		// Right mouse click to select a sender
		// See also IDM_SELECT
		receiver.SelectSender();
		break;

	case WM_KEYUP:
		// SPACEBAR to hide/show on-screen info
		if(wParam == 0x20)
			bShowInfo = !bShowInfo;
		break;
    
	case WM_DESTROY:
        PostQuitMessage(0);
        break;

    default:
        return DefWindowProc(hWnd, message, wParam, lParam);
    }
    return 0;
}


void ShowSenderInfo(HDC hdc)
{
	std::string str = "[";
	str += receiver.GetSenderName();
	str += "]  :  ";
	str += std::to_string(receiver.GetSenderWidth()); str += "x";
	str += std::to_string(receiver.GetSenderHeight());

	// Sender texture format
	DWORD dwformat = receiver.GetSenderFormat();
	str += "   ";
	// Formats can be :
	// 87 - DXGI_FORMAT_B8G8R8A8_UNORM (default)
	// 28 - DXGI_FORMAT_R8G8B8A8_UNORM
	// 24 - DXGI_FORMAT_R10G10B10A2_UNORM
	// 11 - DXGI_FORMAT_R16G16B16A16_UNORM
	// 10 - DXGI_FORMAT_R16G16B16A16_FLOAT
	// 02 - DXGI_FORMAT_R32G32B32A32_FLOAT
	switch (dwformat) {
		case 87: str += "8 bit BGRA";	break;
		case 28: str += "8 bit RGBA";	break;
		case 24: str += "10 bit RGBA";	break;
		case 11: str += "16 bit RGBA";	break;
		case 10: str += "16 bit RGBA float"; break;
		case 02: str += "32 bit RGBA float"; break;
	}

	// Show sender fps and framecount if selected
	if (receiver.GetSenderFrame() > 0) {
		str += "   fps ";
		// Average to stabilise fps display
		g_SenderFps = g_SenderFps*.85 + 0.15*receiver.GetSenderFps();
		// Round first or integer cast will truncate to the whole part
		str += std::to_string((int)(round(g_SenderFps)));
		str += "   frame  ";
		str += std::to_string(receiver.GetSenderFrame());
	}
	// White text (can be any colour (00 BB GG RR) hex)
	// e.g. red = 0x000000FF
	DrawString(str, hdc, 0x00FFFFFF, 20, 20);

	// Show the receiving resolution
	if (g_SenderWidth != receiver.GetSenderWidth()
		|| g_SenderHeight != receiver.GetSenderHeight()) {
			str = "Receiving resolution :  ";
			str += std::to_string(g_SenderWidth);
			str += "x";
			str += std::to_string(g_SenderHeight);
			DrawString(str, hdc, 0x00FFFFFF, 20, 45);
	}

	RECT rc{};
	GetClientRect(g_hWnd, &rc);
	str = "Right button - select sender  :  Space - hide info";
	DrawString(str, hdc, 0x00FFFFFF, 100, rc.bottom-35);

}

void DrawString(std::string str, HDC hdc, COLORREF col, int xpos, int ypos)
{
	HFONT hFont, hOldFont;
	hFont = (HFONT)GetStockObject(SYSTEM_FONT);
	if (hFont) {
		hOldFont = (HFONT)SelectObject(hdc, hFont);
		if (hOldFont) {
			// Text colour
			COLORREF oldText = SetTextColor(hdc, col);
			// Transparent background
			SetBkMode(hdc, TRANSPARENT);
			// Display the text string
			TextOutA(hdc, xpos, ypos, str.c_str(), (int)str.length());
			SetTextColor(hdc, oldText);
			SelectObject(hdc, hOldFont);
			DeleteObject(hOldFont);
		}
		DeleteObject(hFont);
	}
} // end text draw


// That's all..
